# Her k8s objesinin farklı versiyonu olacaktır. Lütfen sitesinden kontrol ediniz.
apiVersion: apps/v1
# Oluşturmak istediğiniz k8s objesinin türünü yazıyoruz.
kind: Deployment
# Her objenin 2 ana bileşen config i var.
metadata:
  name: deployment-postgresql
spec:
  selector:
    matchLabels:
      db: db-postgresql
# Burada yöneteceğiniz podların özelliklerini tanımlıyoruz.
  template:
    metadata:
      labels:
        db: db-postgresql
    spec:
      containers:
# Burada sanal pc yi tanımlıyoruz. Bu PC nin tüm özelliklerini burada ekleyebiliriz.
      - name: pod-postgresql
        image: postgres
        resources:
# Burada PC nin kapasitesinin sınırlarını belirliyoruz. CPU gücü şöyle hesaplanır.
# Bir işlemcide 8 çekirdek olsun. Bu CPU nun gücü 8.000 olarak alınır ve buna göre pay edilir.
          limits:
            memory: "1024Mi"
            cpu: "300m"
        ports:
# Burada container in dışarıya açacağı portları getirtiyoruz..
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "baris12345"
