server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: baris12345
    url: jdbc:postgresql://localhost:5433/AuthDB
  jpa:
    hibernate:
      ddl-auto: update